"""Full electrical BOM (BOM.md) for the 24 V install, from the current design data.

Reads out/channels.json (per-figure load @ 24 V), out/clips.json (back-clips),
out/paths.json (continuous runs). Computes supplies, feeds, clips, cable, cost.
(order.py stays the neon cut list; this is the system-level bill.)

    uv run python bom.py
"""
import json, math
from pathlib import Path

OUT = Path(__file__).parent / "out"
ch = json.load(open(OUT / "channels.json"))
clips = json.load(open(OUT / "clips.json"))
bodies = json.load(open(OUT / "paths.json"))

VOLTS = 24.0
SPARE = 1.12                     # order 12 % extra neon (offcuts, tight-corner remakes)
PSU_W, PSU = 320.0, "Mean Well HLG-320H-24 (320 W, IP67, 24 V)"
PSU_LOAD = 0.72                  # target continuous load fraction (longevity)

tot_w = sum(c["watts"] for c in ch)
tot_a = tot_w / VOLTS
tot_m = sum(c["led_m"] for c in ch)
feeds = sum(c["feeds"] for c in ch)
nclip = len(clips["clips"])
ends  = 2 * len(bodies)          # each continuous run has 2 physical strip ends
psu_n = math.ceil(tot_w / (PSU_W * PSU_LOAD))
dc_m   = round(feeds * 3.5 * 1.2)   # feeds spread over the soffit, ~3.5 m home-run each, +20 % dressing
mains_m = round(psu_n * 5 + 15)     # ~5 m per PSU drop + a spine

def money(x): return f"${x:,.0f}"

usd = {}
usd["Neon 24 V silicone flex, coloured (per profile), +12 %"] = tot_m * SPARE * 2.5
usd[PSU] = psu_n * 60
usd["ESP32 dev board (1 ceiling controller + 2 pillar sensors)"] = 3 * 8
usd["8-ch logic-level MOSFET (IRLB3034PBF) + heatsinks/gate res."] = 8 * 4 + 10
usd["Load cell + HX711 amp (per pillar)"] = 2 * 15
usd["IP67 neon feed connectors / end caps"] = feeds * 3 + ends * 1.5
usd["Stainless back-clips (through-slot mounting)"] = math.ceil(nclip * 1.12) * 0.25
usd["2-core DC distribution cable 2.5 mm2"] = dc_m * 1.1
usd["Mains cable + fused spur to PSUs"] = mains_m * 1.4
usd["Heat-shrink, WAGO, ferrules, cable clips, misc"] = 120
subtotal = sum(usd.values())

L = []; A = L.append
A("# Electrical BOM — People in Orbit (24 V)\n")
A(f"_Auto-generated by `bom.py` from the current design. Load: "
  f"**{tot_w:.0f} W / {tot_a:.1f} A @ {VOLTS:.0f} V**, {tot_m:.0f} m neon, "
  f"{feeds} power feeds, {len(bodies)} continuous runs, {nclip} clips._\n")

A("## Load per channel (one PWM channel / MOSFET per colour)\n")
A("| colour | length | power | current | feeds |")
A("|--------|--------|-------|---------|-------|")
for c in ch:
    A(f"| {c['colour']:7} | {c['led_m']:5.1f} m | {c['watts']:4} W | {c['amps']:4.1f} A | {c['feeds']} |")
A(f"| **total** | **{tot_m:.0f} m** | **{tot_w:.0f} W** | **{tot_a:.1f} A** | **{feeds}** |\n")

A("## Power supplies\n")
A(f"- **{psu_n} x {PSU}** — {psu_n*PSU_W:.0f} W installed vs {tot_w:.0f} W load "
  f"(~{tot_w/(psu_n*PSU_W)*100:.0f} % loaded). Mount distributed up near the soffit, "
  f"each feeding its local zone — keep 24 V DC runs short. Dimming is downstream (MOSFET PWM), "
  f"so a plain constant-voltage supply is fine.\n")

A("## Control\n")
A("- **1 x ESP32** (ceiling) — 8x LEDC PWM -> 8 MOSFETs, common-anode (switch the 24 V return).")
A(f"- **8 x IRLB3034PBF** logic-level N-MOSFET (or an 8-ch >=16 A trigger board) — blue channel peaks "
  f"{max(c['amps'] for c in ch):.1f} A, so size gate drive + heatsinking for >=10 A.")
A("- **2 x ESP32 + HX711 + load cell** at the pillars — force-sensing hand-plates, ESP-NOW to the ceiling node.\n")

A("## Neon terminations & mounting\n")
A(f"- **{feeds} feed connectors** (IP67) at the injection points + **~{ends} end caps** for the run ends.")
A(f"- **{math.ceil(nclip*1.12)} stainless back-clips** for the through-slot mounting (incl. spare).\n")

A("## Cable (estimated — refine against final PSU placement)\n")
A(f"- **~{dc_m} m** 2-core 2.5 mm2 for 24 V distribution (PSU -> {feeds} feeds).")
A(f"- **~{mains_m} m** mains + fused spur to the {psu_n} supplies.\n")

A("## Rough cost (electronics only — excl. Trespa panels, aluminium structure, labour)\n")
A("| item | est. |")
A("|------|------|")
for k, v in usd.items():
    A(f"| {k} | {money(v)} |")
A(f"| **subtotal** | **{money(subtotal)}** |\n")
A("_Order-of-magnitude USD; confirm against suppliers. Neon @ ~$2.5/m, PSU @ ~$60. "
  "Excludes the boards (Trespa), aluminium ceiling profiles, and install labour._")

(Path(__file__).parent / "BOM.md").write_text("\n".join(L) + "\n")
print(f"wrote BOM.md  ·  {tot_w:.0f} W / {tot_a:.1f} A @ {VOLTS:.0f} V  ·  "
      f"{psu_n} PSU  ·  {feeds} feeds  ·  {nclip} clips  ·  ~{money(subtotal)} electronics")
